### ISSUE TITLE
Failed to parse manifest

### ISSUE THREAD

**Issue by danilopopeye** [brunograsselli/overtime#6]
```
Application Cache Error event: Failed to parse manifest http://brunograsselli.github.io/overtime/overtime.appcache 
```

Mac Chrome Version 32.0.1700.102

**Comment by brunograsselli** [comment]
Really? I thought I had removed the cache.

**Comment by danilopopeye** [comment]
![screen shot 2014-02-17 at 16 30 26](https://f.cloud.github.com/assets/27297/2187082/dbc84de6-97f0-11e3-9f20-849b5f69e438.png)

also, looks like you have reverted that commit :point_right: 4fa27e8b65549b20849f2fca5172b39439f5eb60
